repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.262
    hooks:
      - id: ruff
        args:
          - '--fix'

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - '--skip-string-normalization'
          - '--line-length'
          - '120'

  - repo: https://github.com/pdm-project/pdm
    rev: 2.9.2
    hooks:
      - id: pdm-export
        args:
          - -o
          - 'requirements.txt'
          - '--without-hashes'
        files: ^pdm.lock$
