repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
        args:
          - '--fix'
      - id: ruff-format

  - repo: https://github.com/pdm-project/pdm
    rev: 2.17.1
    hooks:
      - id: pdm-export
        args:
          - -o
          - 'requirements.txt'
          - '--without-hashes'
        files: ^pdm.lock$
